[package]
name = "tum-presentation"
version = "0.1.0"
entrypoint = "theme.typ"
authors = ["Robert Jandow <robert@jandow.de>"]
license = "MIT"
description = "Touying slides in the TUM corporate design."
repository = "https://github.com/robertjndw/typst-tum-presentation"
categories = ["presentation"]
compiler = "0.15.0"
keywords = ["TUM", "slides", "touying", "university"]
exclude = [".agents", ".github", "example.typ"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
